### ISSUE TITLE
remove exe

### ISSUE THREAD

**Issue by 3052** [g0ngjie/tvlive#1]
should not store in version control:

https://github.com/g0ngjie/tvlive/blob/master/__run-amd64-0.0.1.exe

**Comment by Nyakooo** [comment]
Thanks, it has been deleted.

**Comment by 3052** [comment]
you have to remove it from every single commit, otherwise its still in the repo:

https://github.com/g0ngjie/tvlive/tree/cc8bf5691e5383403be44b735f2cb6aa94a6d80d

**Comment by Nyakooo** [comment]
Thank you for the reminder. It has been cleaned up
